import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";
import { ThemeProvider } from "@/components/theme-provider";

import { DM_Sans } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const dm_sans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${dm_sans.className} antialiased`}>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <div>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
